export const global = {
  props: {
    header_bg_color: '#1ECCB0',
    header_text_color: '#08332C',
    header_nav_hover_color: '',
    header_title_color: '#08332C',
    header_border_color: '',
    header_icon_color: '#1E7B74',
    header_cart_notification_bg_color: '',
    header_cart_notification_text_color: '',
    search_bg_color: '#F5F5F5',
    search_text_color: '#141414',
    search_icon_color: '',
    search_placeholder_color: '#B5B5B5',
    search_border_color: '#B5B5B5',
    hamburger_icon_color: '',
    back_icon_color: '#08332C',

    footer_bg_color: '',
    footer_text_color: '#000000A6',
    footer_border_color: '',
    footer_nav_hover_color: '',

    primary_main_color: '#1ECCB0', //   Primary=Green',
    primary_dark_color: '#1E7B74',
    primary_darkest_color: '#08332C',
    primary_light_color: '#8AE5D6',
    secondary_color: '#6D17CE', //  Secondary=purple',
    secondary_dark: '',
    secondary_light: '#F0E8FA',
    tertiary_bg: '#F5F5F5', //light grey bg & FFFFFF &E8FAF7',
    button_primary_color: '#1ECCB0', //  //this is BG',
    button_secondary_color: '#FFFFFF',
    button_secondary_border_color: '#E0E0E0',
    button_tertiary_color: '#FFFFFF',
    button_primary_label_color: '#08332C',
    button_secondary_label_color: '#1E7B74',
    button_tertiary_label_color: '#1E7B74',
    button_add_to_cart_label_color: '',
    button_add_to_cart_color: '',
    info_text: '#000000A6',
    info_bg: '',
    info_border: '',
    warning_text: '#F06D0F',
    warning_bg: '#FEF0E7',
    error_text: '#F50031',
    error_bg: '#FEE6EA',
    error_border: '#F50031',
    success_text: '#25AB21',
    success_bg: '#A7F6E9',
    success_border: '',
    body_bg_color: '#FFFFFF',
    text_body_color: '#141414',
    subtitle: 'rgba(0, 0, 0, 0.65)', // 000000A6
    title: '#141414',
    text_disabled_color: '#B5B5B5',
    backdrop_color: '#FFFFFF',
    badge_text_color: '#FFFFFF',
    badge_bg: '#6D17CE',
    text_heading_link_color: '',
    text_sale_price_color: '',
    text_price_color: '',
    text_strikethrough_price_color: '',
    text_discount_color: '',
    offer_text_color: '#D9008D',
    offer_bg_color: '#FCF0F5',
    pink: '#D9008D',
    pink_bg: '#FBE5F4'
  }
}
